apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMRENDQXBTZ0F3SUJBZ0lRQmswZ1hjVU00aEdMc1R3WHNjazlVekFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlSaU9EUmtaRGhoTkMxbU5HWTRMVFF6TmpZdE9HWXpZeTFqTWpNNU5HUmlPR00zWldNdwpJQmNOTWpFeE1qQXlNVEV6T0RJeldoZ1BNakExTVRFeE1qVXhNak00TWpOYU1DOHhMVEFyQmdOVkJBTVRKR0k0Ck5HUmtPR0UwTFdZMFpqZ3RORE0yTmkwNFpqTmpMV015TXprMFpHSTRZemRsWXpDQ0FhSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0dQQURDQ0FZb0NnZ0dCQU1penU2aC9NamFMTHFpTWRJMEd6Y2N4TnpTTWFaMVFROVZDZitSNApMU1g0ZS9HUnpMREVBOU9tOFptZG9DUHA5YTZHc0plRTBTWERwdFk4Uk85YmZ5a2x3NlhQSjlaUzlrZnpGQkJmCndVMmFTRXRTMElLSEtZbFU1UW03c2ttZUh2cVF5MWlrWE5FOVhWd0dsdXQvK1E5Y29wNThtMzFwZitRMk1PRkEKdDdCV2Jzc2Zla3cydlo3ZGFqa2lkem1YU3FrK2pvRk40bWc5NzViNHVKVFRwbUh0d0Q3YngvdHRZeGN0dTdIWgozUFZxeFNzV1lYZkJwWjJZVWNPZDB3WmlzekN1TXVDUDhQK0JhV0JvcUZORFZKZXkvUjFXUEVTa3ZaTS9WVHNlCitlNnlhcnZMd2luS25Fd3NIK2xRTUUwc3Jza1QwcGNXS0FXNUFpN056VDhrNGM2cEJZVDExeFRFek9RaGJMZkgKZ1JFbFBKcDdJOGxqNEdnRVFmc0szcUlhdHcvblphSC9rWjlCSXFTcFBVRHB2clQwd0VYOEtiZ2pVRXlWbkhKYQo2RHVtcWtZOWc0ekJjVE5Od3VleTZyQUJaMHdkUlBUN2RISzB4SkpZYkdRUk90ZkkzRFV4QjBZU1ZBRDFtd1pNCkRTNmREaWlxTG5Fb2Z6ZHFiaUNINkhDVTd3SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQWdRd0R3WUQKVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVCbWJmalQveTBhYU9CN1RzelJsYXcyTVA2SDh3RFFZSgpLb1pJaHZjTkFRRUxCUUFEZ2dHQkFDZnYvN2NPUTMzeHdNdDlwNU11WUpIVTc2OWhYZEFCNkQvU2E1UTZJcDJ1Ckl5VkZPWmh2b3RCNkdFdEZiakxGRCtVdFd6TVBjaVpaS3kvZS81akFMd3A4YWtZOVBON05aN25DMnYvMERPUXkKQm9FUVFqckN6TmtIZFZOSXhmRWpnQjkvcUNMcW8wVS9lK0EvdzREMzI1TVlaSUZta09haWJOZm1NaUM5cURtcgphazBDOTRFWG1PSmtmZUtFdmRFOFM2eDJTL3IxaS9ScnVzOFFab0xsWVBZTU9TcDRHdmt4UWlNcFNjOExVZmdFCnhlNzdqekxMU0RzTWpzRkM1TTFPT2c3S3NVUm1vVS92VWowaE1wQjNob01SL254c0h0VnVxL29lR1QzNFVQRlMKaWVYYzNPbGpHZUFacTYvT3I2TGkxOU5YSjZ5b1Y5OUpnZHA5dUlZaEQ0cG45cFRjZXpJd1VyVktsNmRjbjlsTwoyNHcyTXJob1JjdWRxNXBpZnIwbUxRcUx2SFVuZ00yUXNFQThFSmJEaUpVR0NTZTlHRHRwSHRYM3poNkVXMG9TCmhHNFJ1RXZITzlGUXRsYnY5ZWEycnBuc2c3dDRlL2xmNEdhNmxpaEJZZEFZcFVkcnExYngyYlZKcFhrK3RZQ1EKUGU3dEhiN0o4ZHgyUVhOaXNNSmc3UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://35.200.222.138
  name: gke_compact-record-332904_asia-south1-a_cluster1
contexts:
- context:
    cluster: gke_compact-record-332904_asia-south1-a_cluster1
    user: gke_compact-record-332904_asia-south1-a_cluster1
  name: gke_compact-record-332904_asia-south1-a_cluster1
current-context: gke_compact-record-332904_asia-south1-a_cluster1
kind: Config
preferences: {}
users:
- name: gke_compact-record-332904_asia-south1-a_cluster1
  user:
    auth-provider:
      config:
        cmd-args: config config-helper --format=json
        cmd-path: /usr/lib/google-cloud-sdk/bin/gcloud
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp