apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-usage-info
  labels:
    app: pod-usage-info
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-usage-info
  template:
    metadata:
      labels:
        app: pod-usage-info
    spec:
      containers:
      - image: asia.gcr.io/compact-record-332904/jenkins-assignment:v1
        imagePullPolicy: Never
        name: pod-usage-info
        ports:
        - containerPort: 8080